load and check credentials

diff --git a/twtr b/twtr
--- a/twtr
+++ b/twtr
@@ -1,14 +1,41 @@
 #!/bin/bash
 
-CONFIG_FILE="./.config"
+CONFIG_FILE=./.config
 
-if [ -r $CONFIG_FILE  ]; then
-	. $CONFIG_FILE
-else
-	printf "Config file not found\n"
-	exit 1
-fi
+loadConfig()
+{
+	if [ -r "$CONFIG_FILE" ]; then
+		. $CONFIG_FILE
+	else
+		printf "Config file not found\n"
+		exit 1
+	fi
+}
 
-echo $ACCESS_TOKEN
+checkCredentials()
+{
+	if [ -z "$CONSUMER_KEY" ]; then
+		errorMessage+="Consumer key (API key) not found\n"
+	fi
+	if [ -z "$CONSUMER_SECRET" ]; then
+		errorMessage+="Consumer secret (API secret) not found\n"
+	fi
+	if [ -z "$ACCESS_TOKEN" ]; then
+		errorMessage+="Access token not found\n"
+	fi
+	if [ -z "$ACCESS_SECRET" ]; then
+		errorMessage+="Access secret not found\n"
+	fi
+
+	if [ -n "$errorMessage" ]; then
+		printf "$errorMessage"
+	fi
+}
+
+loadConfig
+checkCredentials
+
+printf "Access token: %s\n" $ACCESS_TOKEN
+printf "Access secret: %s\n" $ACCESS_SECRET
 
 exit
